### ISSUE TITLE
The folder contains all pre-trained models is showing 404 folder not found.

### ISSUE THREAD

**Issue by awais-yaqoob-ml** [MosbehBarhoumi/VITON-PRE-PROCESSING#1]
First of all, wonderful project. Thanks for your efforts. The link is showing 404 error. Need your guidance about it. Thanking in advance.

**Comment by MosbehBarhoumiRAI** [comment]
Hello @awais-yaqoob-ml , It should be fixed thank you !

**Comment by awais-yaqoob-ml** [comment]
@MosbehBarhoumi Thanks man. you are awesome.
